dataTypeInfo.dataTypeName=DataType名
dataTypeInfo.kata=型
dataTypeInfo.minLength=長さ最小
dataTypeInfo.maxLength=長さ最大
dataTypeInfo.stringDataPtn=データパターン（日本語）
dataTypeInfo.stringAllowsProhibitedCharacters=禁則文字チェック除外
dataTypeInfo.stringRegEx=正規表現
dataTypeInfo.stringRegExDescLangDefault=パターン説明（デフォルト言語）
dataTypeInfo.stringRegExDescLangSupport01=パターン説明（追加言語1）
dataTypeInfo.stringRegExDescLangSupport02=パターン説明（追加言語2）
dataTypeInfo.stringRegExDescLangSupport03=パターン説明（追加言語3）
dataTypeInfo.numMinVal=数値系の場合の入力項目：最小値
dataTypeInfo.numMaxVal=数値系の場合の入力項目：最大値
dataTypeInfo.numDigitInteger=数値系の場合の入力項目：整数部桁数
dataTypeInfo.numDigitFraction=数値系の場合の入力項目：小数部桁数
dataTypeInfo.enumCodeLength=Enumの場合：コードの長さ
dataTypeInfo.notNeedsTimezone=日時の場合：timezoneなし
dataTypeInfo.remarks=備考
