#
# Copyright © 2012 ecuacion.jp (info@ecuacion.jp)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

dataTypeRootInfo.dataTypeList=dataType Definition
dataTypeInfo.dataTypeName=DataType Name
dataTypeInfo.kata=Type
dataTypeInfo.minLength=Min Length
dataTypeInfo.maxLength=Max Length
dataTypeInfo.stringDataPtn=Data Pattern
dataTypeInfo.stringAllowsProhibitedCharacters=Exclude Prohibited Chars Check
dataTypeInfo.stringRegEx=Regex
dataTypeInfo.stringRegExDescLangDefault=Pattern Desc (Default Lang)
dataTypeInfo.stringRegExDescLangSupport01=Pattern Desc (Additional Lang 1)
dataTypeInfo.stringRegExDescLangSupport02=Pattern Desc (Additional Lang 2)
dataTypeInfo.stringRegExDescLangSupport03=Pattern Desc (Additional Lang 3)
dataTypeInfo.numMinVal=Min Value
dataTypeInfo.numMaxVal=Max Value
dataTypeInfo.numDigitInteger=Integer Digits
dataTypeInfo.numDigitFraction=Decimal Digits
dataTypeInfo.enumCodeLength=Code Length
dataTypeInfo.notNeedsTimezone=No Timezone
dataTypeInfo.remarks=Notes

dbOrClassColumnInfo.name=Column Name
dbOrClassColumnInfo.dataType=dataType
dbOrClassColumnInfo.isJavaOnly=Java Only
dbOrClassColumnInfo.isSurrogateKey=Surrogate key
dbOrClassColumnInfo.isNaturalKey=natural key (unique key)
dbOrClassColumnInfo.isNullable=nullable
dbOrClassColumnInfo.isAutoIncrement=Auto Numbering
dbOrClassColumnInfo.isForcedIncrement=Force Numbering
dbOrClassColumnInfo.isAutoUpdate=Auto Update
dbOrClassColumnInfo.isForcedUpdate=Force Update
dbOrClassColumnInfo.isCustomGroupColumn=Group Identifier
dbOrClassColumnInfo.springAuditing=Spring Audit
dbOrClassColumnInfo.relationKind=Relation: Type
dbOrClassColumnInfo.relationDirection=Relation: Direction
dbOrClassColumnInfo.relationFieldName=Relation: Source Var Name
dbOrClassColumnInfo.relationSrcObjVarName=Relation: Source Object Var Name
dbOrClassColumnInfo.relationRefTable=Relation: Target Table
dbOrClassColumnInfo.relationRefCol=Relation: Target Column
dbOrClassColumnInfo.relationRefFieldName=Relation: Target Var Name
dbOrClassColumnInfo.relationIsEager=Relation: Eager
dbOrClassColumnInfo.index1=index1
dbOrClassColumnInfo.index2=index2
dbOrClassColumnInfo.index3=index3
dbOrClassColumnInfo.index4=index4
dbOrClassColumnInfo.index5=index5
dbOrClassColumnInfo.index6=index6
dbOrClassColumnInfo.index7=index7
dbOrClassColumnInfo.index8=index8
dbOrClassColumnInfo.index9=index9
dbOrClassColumnInfo.index10=index10
dbOrClassColumnInfo.userFriendlyName=Column Display Name (Default Lang)
dbOrClassColumnInfo.supportedLang1=Column Display Name (Additional Lang 1)
dbOrClassColumnInfo.supportedLang2=Column Display Name (Additional Lang 2)
dbOrClassColumnInfo.supportedLang3=Column Display Name (Additional Lang 3)

dbOrClassTableInfo.name=Table Name

enumClassInfo.dataTypeName=DataType Name

enumValueInfo.isJavaOnly=Java Only
enumValueInfo.code=code
enumValueInfo.varName=varName
enumValueInfo.dispNameDefaultLang=Display Name (Default Lang)
enumValueInfo.dispNameLang1=Display Name (Additional Lang 1)
enumValueInfo.dispNameLang2=Display Name (Additional Lang 2)
enumValueInfo.dispNameLang3=Display Name (Additional Lang 3)

tableListRootInfo.tableList=table list
tableListInfo.tableName=Table Name
tableListInfo.dispNameDefaultLang=Table Display Name (Default Lang)
tableListInfo.dispNameLang1=Table Display Name (Additional Lang 1)
tableListInfo.dispNameLang2=Table Display Name (Additional Lang 2)
tableListInfo.dispNameLang3=Table Display Name (Additional Lang 3)

systemCommonRootInfo.templateVersion=Template version of this Excel file
systemCommonRootInfo.systemName=System name
systemCommonRootInfo.basePackage=Common part of the package name
systemCommonRootInfo.frameworkKind=Framework type
systemCommonRootInfo.characterEncoding=Source code character encoding ("UTF-8" recommended)
systemCommonRootInfo.defaultLang=Default language
systemCommonRootInfo.supportLang1=Support language 1
systemCommonRootInfo.supportLang2=Support language 2
systemCommonRootInfo.supportLang3=Support language 3
systemCommonRootInfo.prohibitedChars=Prohibited characters
systemCommonRootInfo.prohibitedCharsDescDefaultLang=Prohibited chars pattern description (default language)
systemCommonRootInfo.prohibitedCharsDescSupportLang1=Prohibited chars pattern description (additional language 1)
systemCommonRootInfo.prohibitedCharsDescSupportLang2=Prohibited chars pattern description (additional language 2)
systemCommonRootInfo.prohibitedCharsDescSupportLang3=Prohibited chars pattern description (additional language 3)

miscGroupRootInfo.columnName=Column name for group restriction
miscGroupRootInfo.dataTypeName=DataType Name
miscGroupRootInfo.tableNamesWithoutGrouping=Table Names Without Grouping

miscOptimisticLockRootInfo.columnName=Column name for optimistic locking

miscSoftDeleteRootInfo.columnName=Column name for logical delete flag
miscSoftDeleteRootInfo.dataTypeName=DataType Name
miscSoftDeleteRootInfo.initialValue=Initial value (before logical delete)
miscSoftDeleteRootInfo.updatedValue=Update value (after logical delete)
