/*
 * Copyright © 2012 ecuacion.jp (info@ecuacion.jp)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jp.ecuacion.tool.codegenerator.core.generator.systemcommon;

import java.io.IOException;
import jp.ecuacion.tool.codegenerator.core.dto.SystemCommonRootInfo;
import jp.ecuacion.tool.codegenerator.core.enums.DataKindEnum;
import jp.ecuacion.tool.codegenerator.core.generator.AbstractGen;
import jp.ecuacion.tool.codegenerator.core.generator.propertiesfile.PropertiesFileGen;

/** Generates miscellaneous system-common files such as the messages base properties file. */
public class Miscellaneous extends AbstractGen {

  /** Constructs an instance for the system-common data kind. */
  public Miscellaneous() {
    super(DataKindEnum.SYSTEM_COMMON);
  }

  @Override
  public void generate() throws IOException, InterruptedException {

    // // Generate the configuration file required by PropertiesFileUtil
    // generatePropertiesFileUtilProperties(info.getSysCmnRootInfo());

    // Generate the message file for BizLogicAppException contained in sources generated by
    // code-generator
    generateMessagesBaseProperties(info.getSysCmnRootInfo());
  }

  /**
   * Generates the messages_project_base properties files for each configured language
   * by copying the template from the classpath resources directory.
   */
  private void generateMessagesBaseProperties(SystemCommonRootInfo sysCmnRootInfo)
      throws IOException, InterruptedException {
    // Get the list of languages
    String[] langs =
        new String[] {"", sysCmnRootInfo.getDefaultLang(), sysCmnRootInfo.getSupportLang1(),
            sysCmnRootInfo.getSupportLang2(), sysCmnRootInfo.getSupportLang3()};

    PropertiesFileGen pfGen = new PropertiesFileGen();

    // Copy and create from messages_project_base_xx.properties in src/main/resources
    for (String lang : langs) {
      if (lang == null) {
        continue;
      }

      pfGen.copyFileToResourceDir(info.getSystemName(), "src/main/resources", "messages_project",
          "base", lang, "messages", "base", lang);
    }
  }

}
